import random
character=[
'Amber', 'Amber', 'Amber',
'Barbara', 'Barbara', 'Barbara',
'Beidou', 'Beidou', 'Beidou',
'Bennett', 'Bennett', 'Bennett', 
'Chongyun', 'Chongyun', 'Chongyun',
'Diona', 'Diona', 'Diona', 
'Fischl', 'Fischl', 'Fischl',
'Gorou', 'Gorou', 'Gorou',
'Kaeya', 'Kaeya', 'Kaeya',
'Kujou Sara', 'Kujou Sara', 'Kujou Sara',
'Lisa', 'Lisa', 'Lisa',
'Ningguang', 'Ningguang', 'Ningguang',
'Noelle', 'Noelle', 'Noelle',
'Razor', 'Razor', 'Razor',
'Rosaria', 'Rosaria', 'Rosaria',
'Sayu', 'Sayu', 'Sayu',
'Sucrose', 'Sucrose', 'Sucrose',
'Thoma', 'Thoma', 'Thoma',
'Xiangling', 'Xiangling', 'Xiangling',
'Xingqiu', 'Xingqiu', 'Xingqiu',
'Xinyan', 'Xinyan', 'Xinyan',
'Yanfei', 'Yanfei', 'Yanfei',
'Yun Jin', 'Yun Jin', 'Yun Jin',
 'Jean',
 'Diluc',
 'Mona',
 'Keqing',
 'Qi Qi',
 'Klee',
 'Venti',
 'Tartaglia',
 'Zhongli',
 'Albedo',
 'Ganyu',
 'Xiao',
 'Hu Tao',
 'Eula',
 'Kazuha',
 'Yoimiya',
 'Ayaka',
 ' Raiden',
 'Itto',
 'Kokomi',
 'Shenhe',
 'Yae Miko',
 'Ayato',
 'Yelan',
 'Yao Yao',
 'Madame Ping',
 'Timmy',
 'a Hilichurl',
 'a Psyduck',
 'hurlicurl'
]

randomArrayItem=random.choice(character)

print(randomArrayItem)